steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/techradar:latest || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/techradar:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/techradar:latest',
      '.'
    ]
images: ['gcr.io/$PROJECT_ID/techradar:latest']

