steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args: ["--dockerfile=./Dockerfile",
           "--cache=true",
           "--destination=gcr.io/qaware-techradar/techradar:latest"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'techradar', '--image', 'gcr.io/$PROJECT_ID/techradar', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions','deploy','get-source-as-csv','--region','europe-west1','--source','./function-source','--trigger-http','--allow-unauthenticated']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions','deploy','upload-CSV-to-source','--region','europe-west1','--source','./function-upload','--trigger-http','--allow-unauthenticated']