steps:
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
        - '-c'
        - |
          docker pull gcr.io/qaware-techradar/techradar:latest || exit 0
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/qaware-techradar/techradar:latest',
      '--cache-from', 'gcr.io/qaware-techradar/techradar:latest',
      '.'
    ]

  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/techradar', '.' ]
# Push the container image to container tegistry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/techradar']
# Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'techradar', '--image', 'gcr.io/$PROJECT_ID/techradar', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']
images:
  - 'gcr.io/qaware-techradar/techradar'


