steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args: ["--dockerfile=./Dockerfile",
           "--cache=true",
           "--destination=gcr.io/qaware-techradar/techradar:latest"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'techradar', '--image', 'gcr.io/$PROJECT_ID/techradar', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - GetSource
      - --source=./function-source
      - --trigger-http
      - --region=eu-west1
      - --allow-unauthenticated