steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/qaware-techradar/techradar
      - --cache=true
      - --cache-ttl=0h

images: ['gcr.io/qaware-techradar/techradar:latest']



