steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - --destination=gcr.io/$PROJECT_ID/techradar:latest
      - --cache=true
      - --cache-ttl=6h

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'techradar', '--image', 'gcr.io/$PROJECT_ID/techradar', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

images: ['gcr.io/$PROJECT_ID/techradar:latest']

