steps:
  # call with http post https://europe-west1-qaware-techradar.cloudfunctions.net/upload-csv Authorization:"Bearer $(gcloud auth print-identity-token)" name==radar-data
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'upload-csv', '--entry-point', 'uploadCsv', '--runtime', 'nodejs10', '--region', 'europe-west1', '--source', './functions/upload-csv-http', '--trigger-http', '--memory', '512', '--timeout', '120']
