steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args: ["--dockerfile=./Dockerfile",
           "--cache=true",
           "--destination=gcr.io/qaware-techradar/techradar:latest"]

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'techradar', '--image', 'gcr.io/$PROJECT_ID/techradar', '--region', 'europe-west1', '--platform', 'managed', '--allow-unauthenticated']

  # call with http get https://europe-west1-qaware-techradar.cloudfunctions.net/get-source-as-csv
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'get-source-as-csv', '--entry-point', 'getSourceAsCsv', '--runtime', 'nodejs10', '--region', 'europe-west1', '--source', './functions/get-source-as-csv', '--trigger-http', '--allow-unauthenticated']

  # call with http post https://europe-west1-qaware-techradar.cloudfunctions.net/upload-csv Authorization:"Bearer $(gcloud auth print-identity-token)"
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'upload-csv', '--entry-point', 'uploadCsv', '--runtime', 'nodejs10', '--region', 'europe-west1', '--source', './functions/upload-csv-http', '--trigger-http']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['functions', 'deploy', 'get-source-from-storage', '--region', 'europe-west1', '--source', './functions/upload-csv-storage']
